apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: lime
build:
  artifacts:
    - image: neo
      context: app
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: lime
        chartPath: lime
        valuesFiles:
          - lime/values.yaml
        version: 0.1.0
